version: '3'
services:
  skim_001:
    image: arques/argos:latest
    container_name: "argos-skim_001"
    environment:
      - strategy=skim_001
      - mode=live
    volumes:
      - ./:/app
      - ./log/argos/:/log
    ports:
      - 9001:9000
    command: python /app/app.py

  skim_004:
    image: arques/argos:latest
    container_name: "argos-skim_004"
    environment:
      - strategy=skim_004
      - mode=live
    volumes:
      - ./:/app
      - ./log/argos/:/log
    ports:
      - 9002:9000
    command: python /app/app.py