version: '3'
services:
  skim_001:
    image: arques/argos:latest
    container_name: "argos-skim_001"
    environment:
      - strategy=skim_001
      - mode=live
    volumes:
      - ./:/app
      - ./log/argos/:/log
    ports:
      - 6379:5432
    command: python /app/app.py